# Generated by Django 2.1.4 on 2019-02-25 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='citekey',
            field=models.CharField(max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Error: only alphanumeric characters are allowed.')]),
        ),
    ]
