# Generated by Django 2.0.8 on 2018-10-09 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_input'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_input',
        ),
    ]
