# Generated by Django 2.0.8 on 2018-10-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_numberpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='numberpost',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='n_floatNum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='n_smallIntNum',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='NumberPost',
        ),
    ]
