# Generated by Django 2.0.8 on 2018-10-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181022_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='n_boolVal',
            field=models.BooleanField(default=False),
        ),
    ]
