# Generated by Django 2.0.8 on 2018-11-05 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_n_boolval'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isi_val',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Must be a number between 0.0 and 1.0')]),
        ),
    ]
