# Generated by Django 2.0.8 on 2018-11-08 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_isi_val'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combinatorics_roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='isi_val',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Must be a number between 0.0 and 1.0'), django.core.validators.MaxValueValidator(1.0, message=None)]),
        ),
    ]
