# Generated by Django 2.0.8 on 2018-11-15 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_trait'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trait',
        ),
    ]
