# Generated by Django 2.0.8 on 2018-12-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_delete_trait'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Combinatorics_roster',
        ),
    ]
